### ISSUE TITLE
CLI doesnt run

### ISSUE THREAD

**Issue by janderz8** [raamana/neuropredict#4]
Traceback (most recent call last):
  File "/Users/John/anaconda3/bin/neuropredict", line 11, in <module>
    load_entry_point('neuropredict==0.2.4.5', 'console_scripts', 'neuropredict')()
  File "/Users/John/anaconda3/lib/python3.5/site-packages/neuropredict/__main__.py", line 6, in main
    neuropredict.run()

**Comment by raamana** [comment]
This seems to be a problem with compatibility for Python 3.5. Need to make it compatible.
